# docker-compose.yml
version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=snif;Username=admin;Password=yourpassword
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db
    networks:
      - snif-network
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: snif
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - snif-network

networks:
  snif-network:
    driver: bridge

volumes:
  postgres_data: